import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, CheckCircle2, Clock3, FileWarning, RefreshCw, ShieldAlert, Users, XCircle } from 'lucide-react'
import { CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getHodDashboard } from '../../features/hod/dashboard.api'
import { getApiError } from '../../services/apiClient'
import { useAuth } from '../../features/auth/auth.context'
import { Badge } from '../../components/common/Badge'
import { Button } from '../../components/common/Button'
import { EmptyState } from '../../components/common/EmptyState'
import { ErrorState } from '../../components/common/ErrorState'
import { Spinner } from '../../components/common/Spinner'

const STATUS_TONES={pending:'warning',assigned:'info',accepted:'info',inspection:'info',in_progress:'info',resolved:'success',closed:'success',rejected:'danger',reopened:'warning'}
const PRIORITY_TONES={critical:'danger',high:'danger',medium:'warning',low:'neutral'}
const CATEGORY_COLORS=['#2563eb','#16a34a','#d97706','#dc2626','#7c3aed','#0891b2','#64748b']
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
const categoryLabel=v=>String(v||'Unknown').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
const statusLabel=v=>String(v||'Unknown').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
const priorityLabel=v=>String(v||'Unknown').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
const formatDate=v=>{if(!v)return 'Date unavailable';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(d)}
function normalize(data){return {department:data?.department||null,counts:Object.fromEntries(['total','pending','in_progress','resolved','rejected','critical'].map(k=>[k,Number(data?.counts?.[k]||0)])),unassigned:Array.isArray(data?.unassigned_complaints)?data.unassigned_complaints:[],officers:Array.isArray(data?.officer_workload)?data.officer_workload:[],overdue:Array.isArray(data?.overdue_complaints)?data.overdue_complaints:[],monthly:Array.isArray(data?.monthly_data)?data.monthly_data:[],categories:Array.isArray(data?.complaints_by_category)?data.complaints_by_category:[]}}
function Stat({label,value,icon:Icon,tone}){return <article className={`hod-stat hod-stat-${tone}`}><div className="hod-stat-icon"><Icon size={19}/></div><div><p>{label}</p><strong>{value}</strong></div></article>}
export default function HodDashboard(){
 const navigate=useNavigate();
 const {user}=useAuth();const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await getHodDashboard();setData(normalize(r.data))}catch(e){setError(getApiError(e))}finally{setLoading(false)}},[])
 useEffect(()=>{load()},[load])
 const monthly=useMemo(()=>data?.monthly.map(x=>({month:MONTHS[Number(x.month)-1]||x.month,received:Number(x.received||0),resolved:Number(x.resolved||0)}))||[],[data])
 const categories=useMemo(()=>data?.categories.map(x=>({name:categoryLabel(x.category),value:Number(x.count||0)})).filter(x=>x.value>0)||[],[data])
 const officerRows=useMemo(()=>data?.officers.map(x=>({email:x.user__email||'Officer',active:Number(x.active_complaints||0),critical:Number(x.critical_complaints||0),resolved:Number(x.resolved||0)}))||[],[data])
 const name=user?.name||user?.first_name||user?.email?.split('@')[0]||'Department Head'
 if(loading)return <div className="dashboard-loading"><Spinner/><span>Loading your department dashboard…</span></div>
 const header=<header className="dashboard-header"><div><p className="eyebrow">Department head dashboard</p><h1>Good to see you, {name}.</h1><p>{data?.department?.name?`${data.department.name} · ${data.department.code||'Department overview'}`:'Monitor your department’s complaints and service performance.'}</p></div><div className="dashboard-header-actions"><Button variant="secondary" onClick={() => navigate('/hod/complaints')}>Manage complaints</Button><Button variant="secondary" onClick={() => navigate('/hod/statistics')}>View statistics</Button><Button variant="secondary" onClick={() => navigate('/hod/department')}>Department</Button><Button variant="secondary" onClick={load} disabled={loading}><RefreshCw size={16}/>Refresh</Button></div></header>
 if(error)return <section className="dashboard-page hod-dashboard-page">{header}<ErrorState title="Unable to load your department dashboard" description={error.message} onRetry={load}/></section>
 if(!data)return <section className="dashboard-page hod-dashboard-page">{header}<EmptyState title="Dashboard data is unavailable" description="No department dashboard data was returned by the backend."/></section>
 return <section className="dashboard-page hod-dashboard-page">{header}
  <div className="hod-stats"><Stat label="Total complaints" value={data.counts.total} icon={FileWarning} tone="neutral"/><Stat label="Pending" value={data.counts.pending} icon={Clock3} tone="warning"/><Stat label="In progress" value={data.counts.in_progress} icon={AlertTriangle} tone="info"/><Stat label="Resolved" value={data.counts.resolved} icon={CheckCircle2} tone="success"/><Stat label="Rejected" value={data.counts.rejected} icon={XCircle} tone="danger"/><Stat label="Critical" value={data.counts.critical} icon={ShieldAlert} tone="critical"/></div>
  <div className="dashboard-grid hod-dashboard-grid">
   <section className="dashboard-panel dashboard-panel-wide"><div className="panel-heading"><div><p className="panel-eyebrow">Department trend</p><h2>Received vs resolved</h2></div></div>{monthly.length?<div className="chart-container"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthly}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Line type="monotone" dataKey="received" name="Received" stroke="#2563eb" strokeWidth={2.5}/><Line type="monotone" dataKey="resolved" name="Resolved" stroke="#16a34a" strokeWidth={2.5}/></LineChart></ResponsiveContainer></div>:<div className="chart-empty">Monthly department activity is not available yet.</div>}</section>
   <section className="dashboard-panel"><div className="panel-heading"><div><p className="panel-eyebrow">Categories</p><h2>Complaint distribution</h2></div></div>{categories.length?<div className="pie-layout"><div className="pie-chart-container"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="78%" paddingAngle={3} strokeWidth={0}>{categories.map((x,i)=><Cell key={x.name+i} fill={CATEGORY_COLORS[i%CATEGORY_COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="chart-legend">{categories.map((x,i)=><div className="legend-row" key={x.name+i}><span className="legend-dot" style={{background:CATEGORY_COLORS[i%CATEGORY_COLORS.length]}}/><span>{x.name}</span><strong>{x.value}</strong></div>)}</div></div>:<div className="chart-empty">Category distribution is not available yet.</div>}</section>
   <section className="dashboard-panel dashboard-panel-wide"><div className="panel-heading"><div><p className="panel-eyebrow">Officer workload</p><h2>Team performance</h2></div><Users size={20}/></div>{officerRows.length?<div className="hod-officer-table-wrap"><table className="hod-officer-table"><thead><tr><th>Officer</th><th>Active</th><th>Critical</th><th>Resolved</th></tr></thead><tbody>{officerRows.map((x,i)=><tr key={x.email+i}><td title={x.email}>{x.email}</td><td>{x.active}</td><td>{x.critical}</td><td>{x.resolved}</td></tr>)}</tbody></table></div>:<div className="chart-empty">No officer workload data is available yet.</div>}</section>
   <section className="dashboard-panel"><div className="panel-heading"><div><p className="panel-eyebrow">Attention required</p><h2>Overdue complaints</h2></div><AlertTriangle size={20}/></div>{data.overdue.length?<div className="hod-list">{data.overdue.map(x=><article className="hod-list-item" key={x.complaint_id}><div><span className="complaint-id">#{x.complaint_id}</span><h3>{x.title}</h3><p>{x.officer_email||'Unassigned officer'} · {x.days_overdue} day{x.days_overdue===1?'':'s'} overdue</p></div><Badge tone={PRIORITY_TONES[x.priority]||'neutral'}>{priorityLabel(x.priority)}</Badge></article>)}</div>:<div className="recent-empty"><CheckCircle2 size={18}/><span>No overdue complaints are currently reported.</span></div>}</section>
   <section className="dashboard-panel"><div className="panel-heading"><div><p className="panel-eyebrow">Assignment queue</p><h2>Unassigned complaints</h2></div><Users size={20}/></div>{data.unassigned.length?<div className="hod-list">{data.unassigned.map(x=><article className="hod-list-item" key={x.complaint_id}><div><span className="complaint-id">#{x.complaint_id}</span><h3>{x.title}</h3><p>{formatDate(x.created_at)}</p></div><div className="hod-badge-stack"><Badge tone={PRIORITY_TONES[x.priority]||'neutral'}>{priorityLabel(x.priority)}</Badge><Badge tone={STATUS_TONES[x.status]||'neutral'}>{statusLabel(x.status)}</Badge></div></article>)}</div>:<div className="recent-empty"><CheckCircle2 size={18}/><span>No unassigned complaints are currently reported.</span></div>}</section>
  </div></section>
}
